<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_58ca9b4347457',
		'title' => 'Page',
		'fields' => array (
			array (
				'key' => 'field_58ca9b986ac2b',
				'label' => esc_html__('Page Width', 'allstore'),
				'name' => 'page_width',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'container' => esc_html__('Container', 'allstore'),
					'full' => esc_html__('Full Width', 'allstore'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'container',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_58ce7f2f518ac',
				'label' => esc_html__('Title and Breadcrumbs', 'allstore'),
				'name' => 'page_ttl_bcrumbs',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'show_both' => esc_html__('Show Both', 'allstore'),
					'show_ttl' => esc_html__('Show Title', 'allstore'),
					'show_bcrumbs' => esc_html__('Show Breadcrumbs', 'allstore'),
					'hide' => 'Hide Both',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'show_both',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_5893411b791e6',
		'title' => esc_html__('Product', 'allstore'),
		'fields' => array (
			array (
				'key' => 'field_58d48ad3debfd',
				'label' => esc_html__('Description Tab Width', 'allstore'),
				'name' => 'product_descwidth',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'container' => esc_html__('Container', 'allstore'),
					'full' => esc_html__('Full Width', 'allstore'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'container',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_589368c41aefc',
				'label' => esc_html__('Articles', 'allstore'),
				'name' => 'articles',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'post',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
				'ui' => 1,
			),
			array (
				'key' => 'field_5893413c75163',
				'label' => esc_html__('Video', 'allstore'),
				'name' => 'product_video',
				'type' => 'oembed',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'width' => '',
				'height' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_57a03190968da',
		'title' => esc_html__('Post', 'allstore'),
		'fields' => array (
			array (
				'key' => 'field_57a047495c4b4',
				'label' => esc_html__('Related', 'allstore'),
				'name' => 'post_related',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => esc_html__('Add Related Post', 'allstore'),
				'sub_fields' => array (
					array (
						'key' => 'field_57a047635c4b5',
						'label' => esc_html__('Related', 'allstore'),
						'name' => 'related',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'post',
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
			),
			array (
				'key' => 'field_57a047495c4b1',
				'label' => esc_html__('Related Products', 'allstore'),
				'name' => 'post_products',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => esc_html__('Add Related Product', 'allstore'),
				'sub_fields' => array (
					array (
						'key' => 'field_57a047635c4b2',
						'label' => esc_html__('Related Product', 'allstore'),
						'name' => 'related',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'product',
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
			),
			array (
				'key' => 'field_57e20da842fd5',
				'label' => esc_html__('Video', 'allstore'),
				'name' => 'post_video',
				'type' => 'text',
				'instructions' => 'Video URL',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_57e20e639343e',
				'label' => esc_html__('Slider', 'allstore'),
				'name' => 'post_slider',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'preview_size' => 'thumbnail',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
?>